// <auto-generated />
namespace KortKiralamaOdevi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrationfirst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationfirst));
        
        string IMigrationMetadata.Id
        {
            get { return "201804131736277_migration-first"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
